spring:
  thymeleaf:
    cache: false        # HTML 즉시 반영
  devtools:
    restart:
      enabled: true     # 코드 변경 시 서버 자동 재시작
    livereload:
      enabled: true     # 브라우저 자동 새로고침
application:
  name: qube7-homepage
server:
  port: 8080
